spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_booking_management
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ID}
    password: ${APP_PASS_GMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000 #seconds
          timeout: 5000 #seconds
          writetimeout: 5000 #seconds

jwt:
  private_key: ${PRIVATE_KEY}
  access_token_valid_duration: 1800 #seconds
  refresh_token_valid_duration: 86400 #seconds
  issuer: hotel_booking_management

management:
  endpoints:
    web:
      exposure:
        include: beans

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG

mail:
  smtp:
    debug: true

base_url: http://localhost:8080

file:
  upload_folder: uploads/images/
  user_avatar_folder_name: avatars