spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_booking_management
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  private_key: ${PRIVATE_KEY}
  valid_duration: 12 #hours
  issuer: hotel_booking_management

logging:
  level:
    org:
      springframework:
        security: DEBUG

base_url: http://localhost:8080

file:
  upload_folder: uploads/images/
  user_avatar_folder_name: avatars