spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hotel_booking_management"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true